/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import model.Pelanggan;
import model.Pengemudi;

/**
 *
 * @author The Keong's
 */
public class admin extends javax.swing.JPanel {

    /**
     * Creates new form admin
     */
    public admin() {
        initComponents();
    }
    
    public Object getVpel(){
        return vPelanggan;
    }
    
    public Object getVpeng(){
        return vPengemudi;
    }
    
    public Object getlogout(){
        return btnLogout;
    }
    public Object getdelete(){
        return btndelete;
    }
    
    public Object tabelViewSelected(){
        return tview;
    }
    
    public int getselectedview(){
        return tview.getSelectedRow();
    }
    
    public void setview(String s){
        viewriwayat.setText(s);
    }
    
    public void addAdapter(MouseAdapter e) {
        tview.addMouseListener(e);
    }
   public void addListener(ActionListener e) {
        btnLogout.addActionListener(e);
        btndelete.addActionListener(e);
        vPelanggan.addActionListener(e);
        vPengemudi.addActionListener(e);
    }
    
    public void setListOutViewPlg(ArrayList<Pelanggan> list){
        String[] judul = {"Username","No HP","Pass"};
        String[][] isi = new String[list.size()][3];
        int i = 0;
        for (Pelanggan p : list){
            isi[i][0] = p.getNama();
            isi[i][1] = String.valueOf(p.getNo_hp());
            isi[i][2] = p.getPass();
            i++;
        }
        DefaultTableModel tableModel = new DefaultTableModel(isi,judul);
        tview.setModel(tableModel);
        tview.getColumnModel().getColumn(0).setPreferredWidth(20);
    }
    
    public void setListOutViewPng(ArrayList<Pengemudi> list){
        String[] judul = {"Username","No HP","Pass"};
        String[][] isi = new String[list.size()][3];
        int i = 0;
        for (Pengemudi p : list){
            isi[i][0] = p.getNama();
            isi[i][1] = String.valueOf(p.getNo_hp());
            isi[i][2] = p.getPass();
            i++;
        }
        DefaultTableModel tableModel = new DefaultTableModel(isi,judul);
        tview.setModel(tableModel);
        tview.getColumnModel().getColumn(0).setPreferredWidth(20);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tview = new javax.swing.JTable();
        vPelanggan = new javax.swing.JButton();
        vPengemudi = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        viewriwayat = new javax.swing.JTextArea();
        btnLogout = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("MENU ADMIN");

        tview.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        jScrollPane1.setViewportView(tview);

        vPelanggan.setText("view pelanggan");

        vPengemudi.setText("view pengemudi");

        btndelete.setText("DELETE");
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });

        viewriwayat.setColumns(20);
        viewriwayat.setRows(5);
        jScrollPane3.setViewportView(viewriwayat);

        btnLogout.setText("LogOut");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(vPengemudi)
                            .addComponent(vPelanggan))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(btndelete)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67)
                        .addComponent(btnLogout)))
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLogout))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(vPengemudi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(vPelanggan))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btndelete)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btndeleteActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLogoutActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btndelete;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tview;
    private javax.swing.JButton vPelanggan;
    private javax.swing.JButton vPengemudi;
    private javax.swing.JTextArea viewriwayat;
    // End of variables declaration//GEN-END:variables
}
